/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;
import Controlador.Cdatos;
import java.lang.reflect.Array;
import java.util.ArrayList;


/**
 *
 * @author PROGRAMACION 2do A
 */
public class frmDatos extends javax.swing.JFrame
{

    /**
     * Creates new form frmDatos
     */
    public frmDatos()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        buttonGroup1 = new javax.swing.ButtonGroup();
        cbxProvincia = new javax.swing.JComboBox<>();
        cbxCanton = new javax.swing.JComboBox<>();
        cbxParroquia = new javax.swing.JComboBox<>();
        lblProvincia = new javax.swing.JLabel();
        lblCanton = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        lblFechaNaci = new javax.swing.JLabel();
        txtFechaNaci = new javax.swing.JTextField();
        lblEdad = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        lblgenero = new javax.swing.JLabel();
        cbxGenero = new javax.swing.JComboBox<>();
        chbxSoltero = new javax.swing.JCheckBox();
        chbxCasado = new javax.swing.JCheckBox();
        chbxDivorciado = new javax.swing.JCheckBox();
        chbxViudo = new javax.swing.JCheckBox();
        chbxUnion = new javax.swing.JCheckBox();
        lblObservaciones = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowActivated(java.awt.event.WindowEvent evt)
            {
                formWindowActivated(evt);
            }
        });

        cbxProvincia.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cbxProvinciaActionPerformed(evt);
            }
        });

        cbxCanton.setEnabled(false);
        cbxCanton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cbxCantonActionPerformed(evt);
            }
        });

        cbxParroquia.setEnabled(false);
        cbxParroquia.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cbxParroquiaActionPerformed(evt);
            }
        });

        lblProvincia.setText("Provincia");

        lblCanton.setText("Cantón");

        jLabel3.setText("Parroquia");

        lblNombre.setText("Nombre");

        lblApellido.setText("Apellido");

        txtApellido.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtApellidoActionPerformed(evt);
            }
        });

        txtNombre.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtNombreActionPerformed(evt);
            }
        });

        lblFechaNaci.setText("Fecha Nacimiento");

        lblEdad.setText("Edad");

        lblgenero.setText("Genero");

        cbxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Género" }));

        buttonGroup1.add(chbxSoltero);
        chbxSoltero.setText("Soltero");

        buttonGroup1.add(chbxCasado);
        chbxCasado.setText("Casado");

        buttonGroup1.add(chbxDivorciado);
        chbxDivorciado.setText("Divorciado");

        buttonGroup1.add(chbxViudo);
        chbxViudo.setText("Viudo");

        buttonGroup1.add(chbxUnion);
        chbxUnion.setText("Unión Libre");

        lblObservaciones.setText("Observaciones");

        txtObservaciones.setColumns(20);
        txtObservaciones.setRows(5);
        jScrollPane1.setViewportView(txtObservaciones);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnGuardarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(btnGuardar)
                .addGap(299, 299, 299)
                .addComponent(btnSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblApellido)
                        .addGap(18, 18, 18)
                        .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(chbxSoltero)
                                    .addComponent(lblFechaNaci))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(chbxCasado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(chbxDivorciado)
                                        .addGap(18, 18, 18)
                                        .addComponent(chbxViudo)
                                        .addGap(18, 18, 18)
                                        .addComponent(chbxUnion))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtFechaNaci, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblEdad)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblgenero)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(lblObservaciones)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblProvincia)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbxProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblCanton)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbxCanton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbxParroquia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 75, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxCanton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxParroquia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProvincia)
                    .addComponent(lblCanton)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(lblApellido)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaNaci)
                    .addComponent(txtFechaNaci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEdad)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblgenero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbxSoltero)
                    .addComponent(chbxCasado)
                    .addComponent(chbxDivorciado)
                    .addComponent(chbxViudo)
                    .addComponent(chbxUnion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblObservaciones)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalir)
                    .addComponent(btnGuardar))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnGuardarActionPerformed
    {//GEN-HEADEREND:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtNombreActionPerformed
    {//GEN-HEADEREND:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtApellidoActionPerformed
    {//GEN-HEADEREND:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowActivated
    {//GEN-HEADEREND:event_formWindowActivated
        Cdatos objDatos = new Cdatos();
        
        ArrayList Lista = new ArrayList();
        
        Lista = objDatos.cargarProvincias();
        
        cbxProvincia.addItem("Seleccione Provincia");
        
        for (int i = 0; i <Lista.size(); i++)
        {
            cbxProvincia.addItem((String)Lista.get(i).toString());
        
        }
        
        
        
       
        
        
        
        
        
    }//GEN-LAST:event_formWindowActivated

    private void cbxProvinciaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cbxProvinciaActionPerformed
    {//GEN-HEADEREND:event_cbxProvinciaActionPerformed
        int intIndice;
        String strProvincia;
        ArrayList Lista = new ArrayList();
        Cdatos objdatos = new Cdatos();
        cbxCanton.setEnabled(true);
        cbxCanton.removeAllItems();
        
        intIndice = cbxProvincia.getSelectedIndex();
        if (intIndice!=0)
        {
            strProvincia = cbxProvincia.getItemAt(intIndice);
            cbxCanton.addItem("Seleccione Canton");
            Lista = objdatos.cargarCanton(strProvincia);
            for (int i = 0; i < Lista.size(); i++) {
                    cbxCanton.addItem(Lista.get(i).toString());
                }
               
            
        }
        
        
        
        
        
    }//GEN-LAST:event_cbxProvinciaActionPerformed

    private void cbxCantonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cbxCantonActionPerformed
    {//GEN-HEADEREND:event_cbxCantonActionPerformed
       int intIndice;
        String strCanton;
        ArrayList Lista = new ArrayList();

        Cdatos objDatos = new Cdatos();
        cbxCanton.setEnabled(true);

        cbxParroquia.removeAllItems();

        intIndice = cbxCanton.getSelectedIndex();

        if (intIndice != 0) {
           
                strCanton = cbxCanton.getItemAt(intIndice);
                cbxParroquia.setEnabled(true);
                cbxParroquia.addItem("Seleccione Parroquia");

                Lista = objDatos.cargarParroquia(strCanton);
                for (int i = 0; i < Lista.size(); i++) {
                    cbxParroquia.addItem(Lista.get(i).toString());
                }
           
        }
    }//GEN-LAST:event_cbxCantonActionPerformed

    private void cbxParroquiaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cbxParroquiaActionPerformed
    {//GEN-HEADEREND:event_cbxParroquiaActionPerformed
        int intIndice;
        String strProvincia;
        ArrayList lista = new ArrayList();

        Cdatos objDatos = new Cdatos();

        cbxCanton.removeAllItems();

        intIndice = cbxProvincia.getSelectedIndex();

        if (intIndice != 0) {
          
                strProvincia = cbxProvincia.getItemAt(intIndice);

                cbxCanton.addItem("Seleccione Canton");

                lista = objDatos.cargarCanton(strProvincia);
                for (int i = 0; i < lista.size(); i++) {
                    cbxCanton.addItem(lista.get(i).toString());
                }
           

        }
    }//GEN-LAST:event_cbxParroquiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(frmDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(frmDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(frmDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(frmDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new frmDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbxCanton;
    private javax.swing.JComboBox<String> cbxGenero;
    private javax.swing.JComboBox<String> cbxParroquia;
    private javax.swing.JComboBox<String> cbxProvincia;
    private javax.swing.JCheckBox chbxCasado;
    private javax.swing.JCheckBox chbxDivorciado;
    private javax.swing.JCheckBox chbxSoltero;
    private javax.swing.JCheckBox chbxUnion;
    private javax.swing.JCheckBox chbxViudo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblCanton;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblFechaNaci;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblObservaciones;
    private javax.swing.JLabel lblProvincia;
    private javax.swing.JLabel lblgenero;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtFechaNaci;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextArea txtObservaciones;
    // End of variables declaration//GEN-END:variables
}
