/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package puzzle2;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author edu_r
 */
public class panel extends javax.swing.JFrame {

    static int cont = 1;
    int i;

    /**
     * Creates new form panel
     */
    public panel() {
        initComponents();
        setTitle("Puzzle");
        setSize(680, 550);
        setLocationRelativeTo(null);
        setResizable(false);

        btn9.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabelMuestra = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        JMenuMario = new javax.swing.JMenuItem();
        jMenuRobot = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemResolver = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(51, 102, 255));
        setFocusable(false);
        setFocusableWindowState(false);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(500, 500));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(512, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanel1.setLayout(new java.awt.GridLayout(3, 3));

        btn1.setFont(new java.awt.Font("Dialog", 1, 3)); // NOI18N
        btn1.setForeground(new java.awt.Color(255, 255, 255));
        btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1.png"))); // NOI18N
        btn1.setText("1");
        btn1.setToolTipText("");
        btn1.setAlignmentY(1.0F);
        btn1.setBorderPainted(false);
        btn1.setContentAreaFilled(false);
        btn1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn1.setIconTextGap(1);
        btn1.setMaximumSize(new java.awt.Dimension(166, 166));
        btn1.setMinimumSize(new java.awt.Dimension(166, 166));
        btn1.setName(""); // NOI18N
        btn1.setOpaque(true);
        btn1.setPreferredSize(new java.awt.Dimension(166, 166));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn1);

        btn2.setFont(new java.awt.Font("Dialog", 1, 3)); // NOI18N
        btn2.setForeground(new java.awt.Color(255, 255, 255));
        btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2.png"))); // NOI18N
        btn2.setBorderPainted(false);
        btn2.setContentAreaFilled(false);
        btn2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn2.setMaximumSize(new java.awt.Dimension(166, 166));
        btn2.setMinimumSize(new java.awt.Dimension(166, 166));
        btn2.setName(""); // NOI18N
        btn2.setOpaque(true);
        btn2.setPreferredSize(new java.awt.Dimension(166, 166));
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn2);

        btn3.setFont(new java.awt.Font("Dialog", 1, 3)); // NOI18N
        btn3.setForeground(new java.awt.Color(255, 255, 255));
        btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/3.png"))); // NOI18N
        btn3.setBorderPainted(false);
        btn3.setContentAreaFilled(false);
        btn3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn3.setMaximumSize(new java.awt.Dimension(166, 166));
        btn3.setMinimumSize(new java.awt.Dimension(166, 166));
        btn3.setOpaque(true);
        btn3.setPreferredSize(new java.awt.Dimension(166, 166));
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel1.add(btn3);

        btn4.setFont(new java.awt.Font("Dialog", 1, 3)); // NOI18N
        btn4.setForeground(new java.awt.Color(255, 255, 255));
        btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/4.png"))); // NOI18N
        btn4.setBorderPainted(false);
        btn4.setContentAreaFilled(false);
        btn4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn4.setMaximumSize(new java.awt.Dimension(166, 166));
        btn4.setMinimumSize(new java.awt.Dimension(166, 166));
        btn4.setPreferredSize(new java.awt.Dimension(166, 166));
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel1.add(btn4);

        btn5.setFont(new java.awt.Font("Dialog", 1, 3)); // NOI18N
        btn5.setForeground(new java.awt.Color(166, 166, 166));
        btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/5.png"))); // NOI18N
        btn5.setBorderPainted(false);
        btn5.setContentAreaFilled(false);
        btn5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn5.setMaximumSize(new java.awt.Dimension(166, 166));
        btn5.setMinimumSize(new java.awt.Dimension(166, 166));
        btn5.setPreferredSize(new java.awt.Dimension(166, 166));
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel1.add(btn5);

        btn6.setFont(new java.awt.Font("Dialog", 1, 3)); // NOI18N
        btn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/6.png"))); // NOI18N
        btn6.setBorderPainted(false);
        btn6.setContentAreaFilled(false);
        btn6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn6.setMaximumSize(new java.awt.Dimension(166, 166));
        btn6.setMinimumSize(new java.awt.Dimension(166, 166));
        btn6.setPreferredSize(new java.awt.Dimension(166, 166));
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel1.add(btn6);

        btn7.setFont(new java.awt.Font("Dialog", 1, 3)); // NOI18N
        btn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/7.png"))); // NOI18N
        btn7.setBorderPainted(false);
        btn7.setContentAreaFilled(false);
        btn7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn7.setMaximumSize(new java.awt.Dimension(166, 166));
        btn7.setMinimumSize(new java.awt.Dimension(166, 166));
        btn7.setPreferredSize(new java.awt.Dimension(166, 166));
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel1.add(btn7);

        btn8.setFont(new java.awt.Font("Dialog", 1, 3)); // NOI18N
        btn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/8.png"))); // NOI18N
        btn8.setToolTipText("");
        btn8.setBorderPainted(false);
        btn8.setContentAreaFilled(false);
        btn8.setDisabledIcon(null);
        btn8.setDisabledSelectedIcon(null);
        btn8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn8.setMaximumSize(new java.awt.Dimension(166, 166));
        btn8.setMinimumSize(new java.awt.Dimension(166, 166));
        btn8.setName(""); // NOI18N
        btn8.setPreferredSize(new java.awt.Dimension(166, 166));
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel1.add(btn8);

        btn9.setFont(new java.awt.Font("Dialog", 1, 3)); // NOI18N
        btn9.setBorderPainted(false);
        btn9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn9.setMaximumSize(new java.awt.Dimension(166, 166));
        btn9.setMinimumSize(new java.awt.Dimension(166, 166));
        btn9.setPreferredSize(new java.awt.Dimension(166, 166));
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel1.add(btn9);

        jLabelMuestra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mario2.png"))); // NOI18N

        jLabel3.setText("Numero de Movimientos");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabelMuestra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMuestra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        jMenu3.setText("Nuevo");

        jMenu5.setText("Nueva Partida");

        JMenuMario.setText("Imagen 1");
        JMenuMario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuMarioActionPerformed(evt);
            }
        });
        jMenu5.add(JMenuMario);

        jMenuRobot.setText("Imagen 2");
        jMenuRobot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRobotActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuRobot);

        jMenuItem1.setText("Imagen 3");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenu3.add(jMenu5);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setText("Salir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Ayuda");

        jMenuItemResolver.setText("Resolver");
        jMenuItemResolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemResolverActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemResolver);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:

        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void JMenuMarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuMarioActionPerformed
        cont = 0;
        i = 1;
       jLabel2.setText(String.valueOf("0"));
        btn1.setText("1");
        btn2.setText("2");
        btn3.setText("3");
        btn5.setText("4");
        btn6.setText("5");
        btn7.setText("6");
        btn8.setText("7");
        btn9.setText("9");
        this.btn1.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../imagenes/" + 1 + ".png")));
        this.btn2.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../imagenes/" + 2 + ".png")));
        this.btn3.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../imagenes/" + 3 + ".png")));
        this.btn4.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../imagenes/" + 4 + ".png")));
        this.btn5.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../imagenes/" + 5 + ".png")));
        this.btn6.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../imagenes/" + 6 + ".png")));
        this.btn7.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../imagenes/" + 7 + ".png")));
        this.btn8.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../imagenes/" + 8 + ".png")));
        btn1.setVisible(true);
        btn2.setVisible(true);
        btn3.setVisible(true);
        btn4.setVisible(true);
        btn5.setVisible(true);
        btn6.setVisible(true);
        btn7.setVisible(true);
        btn8.setVisible(true);
        btn9.setVisible(false);

        cont = 1;
        int n = 8;  //numeros aleatorios
        int k = n;  //auxiliar;
        int[] numeros = new int[n];
        int[] valor = new int[n];
        Random rnd = new Random();
        int res;

        //se rellena una matriz ordenada del 1 al 9(1..n)
        for (int i = 0; i < n; i++) {
            numeros[i] = i + 1;
        }

        for (int i = 0; i < n; i++) {
            res = rnd.nextInt(k);
            valor[i] = numeros[res];
            numeros[res] = numeros[k - 1];
            k--;
            System.out.println(valor[i]);
        }
        System.out.println("------------------------------------------");

        btn1.setText(String.valueOf(valor[0]));
        btn2.setText(String.valueOf(valor[1]));
        btn3.setText(String.valueOf(valor[2]));
        btn4.setText(String.valueOf(valor[3]));
        btn5.setText(String.valueOf(valor[4]));
        btn6.setText(String.valueOf(valor[5]));
        btn7.setText(String.valueOf(valor[6]));
        btn8.setText(String.valueOf(valor[7]));

        btn9.setVisible(false);//espacio que permite realizar los moviemientos en le PUZZLE

        System.out.println("------------------------------------------");
        this.btn1.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../imagenes/" + valor[0] + ".png")));
        this.btn2.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../imagenes/" + valor[1] + ".png")));
        this.btn3.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../imagenes/" + valor[2] + ".png")));
        this.btn4.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../imagenes/" + valor[3] + ".png")));
        this.btn5.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../imagenes/" + valor[4] + ".png")));
        this.btn6.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../imagenes/" + valor[5] + ".png")));
        this.btn7.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../imagenes/" + valor[6] + ".png")));
        this.btn8.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../imagenes/" + valor[7] + ".png")));
        btn9.setVisible(false);
        jLabelMuestra.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../imagenes/mario2.png")));

    }//GEN-LAST:event_JMenuMarioActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        if (btn6.isVisible() == false) {
            btn6.setText(btn9.getText());
            btn6.setIcon(btn9.getIcon());
            btn6.setVisible(true);
            btn9.setVisible(false);
        }
        if (btn8.isVisible() == false) {
            btn8.setText(btn9.getText());
            btn8.setIcon(btn9.getIcon());
            btn8.setVisible(true);
            btn9.setVisible(false);

        }
        contarMovimiento();
        ordenado();
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        if (btn9.isVisible() == false) {
            btn9.setText(btn8.getText());
            btn9.setIcon(btn8.getIcon());
            btn8.setVisible(false);
            btn9.setVisible(true);
        }
        if (btn5.isVisible() == false) {
            btn5.setText(btn8.getText());
            btn5.setIcon(btn8.getIcon());
            btn5.setVisible(true);
            btn8.setVisible(false);

        }
        if (btn7.isVisible() == false) {
            btn7.setText(btn8.getText());
            btn7.setIcon(btn8.getIcon());
            btn7.setVisible(true);
            btn8.setVisible(false);

        }
        contarMovimiento();
        ordenado();
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        if (btn4.isVisible() == false) {
            btn4.setText(btn7.getText());
            btn4.setIcon(btn7.getIcon());
            btn4.setVisible(true);
            btn7.setVisible(false);
        }
        if (btn8.isVisible() == false) {
            btn8.setText(btn7.getText());
            btn8.setIcon(btn7.getIcon());
            btn8.setVisible(true);
            btn7.setVisible(false);
        }
        contarMovimiento();
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        if (btn9.isVisible() == false) {
            btn9.setText(btn6.getText());
            btn9.setIcon(btn6.getIcon());
            btn6.setVisible(false);
            btn9.setVisible(true);
        }
        if (btn5.isVisible() == false) {
            btn5.setText(btn6.getText());
            btn5.setIcon(btn6.getIcon());
            btn5.setVisible(true);
            btn6.setVisible(false);
        }
        if (btn3.isVisible() == false) {
            btn3.setText(btn6.getText());
            btn3.setIcon(btn6.getIcon());
            btn6.setVisible(false);
            btn3.setVisible(true);
        }
        contarMovimiento();
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        if (btn8.isVisible() == false) {
            btn8.setText(btn5.getText());
            btn8.setIcon(btn5.getIcon());
            btn5.setVisible(false);
            btn8.setVisible(true);

        }
        if (btn6.isVisible() == false) {
            btn6.setText(btn5.getText());
            btn6.setIcon(btn5.getIcon());
            btn5.setVisible(false);
            btn6.setVisible(true);

        }
        if (btn4.isVisible() == false) {
            btn4.setText(btn5.getText());
            btn4.setIcon(btn5.getIcon());
            btn4.setVisible(true);
            btn5.setVisible(false);
        }
        if (btn2.isVisible() == false) {
            btn2.setText(btn5.getText());
            btn2.setIcon(btn5.getIcon());
            btn2.setVisible(true);
            btn5.setVisible(false);
        }
        contarMovimiento();
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        if (btn7.isVisible() == false) {
            btn7.setText(btn4.getText());
            btn7.setIcon(btn4.getIcon());
            btn7.setVisible(true);
            btn4.setVisible(false);

        }
        if (btn5.isVisible() == false) {
            btn5.setText(btn4.getText());
            btn5.setIcon(btn4.getIcon());
            btn4.setVisible(false);
            btn5.setVisible(true);
        }
        if (btn1.isVisible() == false) {
            btn1.setText(btn4.getText());
            btn1.setIcon(btn4.getIcon());
            btn4.setVisible(false);
            btn1.setVisible(true);
        }
        contarMovimiento();
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        if (btn6.isVisible() == false) {
            btn6.setText(btn3.getText());
            btn6.setIcon(btn3.getIcon());
            btn6.setVisible(true);
            btn3.setVisible(false);
        }
        if (btn2.isVisible() == false) {
            btn2.setText(btn3.getText());
            btn2.setIcon(btn3.getIcon());
            btn2.setVisible(true);
            btn3.setVisible(false);
        }

        contarMovimiento();
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        if (btn1.isVisible() == false) {
            btn1.setText(btn2.getText());
            btn1.setIcon(btn2.getIcon());
            btn1.setVisible(true);
            btn2.setVisible(false);
        }
        if (btn3.isVisible() == false) {
            btn3.setText(btn2.getText());
            btn3.setIcon(btn2.getIcon());
            btn3.setVisible(true);
            btn2.setVisible(false);
        }
        if (btn5.isVisible() == false) {
            btn5.setText(btn2.getText());
            btn5.setIcon(btn2.getIcon());
            btn5.setVisible(true);
            btn2.setVisible(false);
        }
        contarMovimiento();
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        if (btn2.isVisible() == false) {
            btn2.setText(btn1.getText());
            btn2.setIcon(btn1.getIcon());
            btn2.setVisible(true);
            btn1.setVisible(false);
        }
        if (btn4.isVisible() == false) {
            btn4.setText(btn1.getText());
            btn4.setIcon(btn1.getIcon());

            btn4.setVisible(true);
            btn1.setVisible(false);
        }
        contarMovimiento();
    }//GEN-LAST:event_btn1ActionPerformed

    private void jMenuItemResolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemResolverActionPerformed
        // TODO add your handling code here:
        btn1.setText("1");
        btn2.setText("2");
        btn3.setText("3");
        btn5.setText("4");
        btn6.setText("5");
        btn7.setText("6");
        btn8.setText("7");
        btn9.setText("9");
        this.btn1.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../imagenes/" + 1 + ".png")));
        this.btn2.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../imagenes/" + 2 + ".png")));
        this.btn3.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../imagenes/" + 3 + ".png")));
        this.btn4.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../imagenes/" + 4 + ".png")));
        this.btn5.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../imagenes/" + 5 + ".png")));
        this.btn6.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../imagenes/" + 6 + ".png")));
        this.btn7.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../imagenes/" + 7 + ".png")));
        this.btn8.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../imagenes/" + 8 + ".png")));
        btn1.setVisible(true);
        btn2.setVisible(true);
        btn3.setVisible(true);
        btn4.setVisible(true);
        btn5.setVisible(true);
        btn6.setVisible(true);
        btn7.setVisible(true);
        btn8.setVisible(true);
        btn9.setVisible(false);

    }//GEN-LAST:event_jMenuItemResolverActionPerformed

    private void jMenuRobotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRobotActionPerformed
        // TODO add your handling code here:
        cont = 0;
        i = 1;
        jLabel2.setText(String.valueOf("0"));
        btn1.setText("1");
        btn2.setText("2");
        btn3.setText("3");
        btn5.setText("4");
        btn6.setText("5");
        btn7.setText("6");
        btn8.setText("7");
        btn9.setText("9");
        this.btn1.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../imagenesRobot/" + 1 + ".png")));
        this.btn2.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../imagenesRobot/" + 2 + ".png")));
        this.btn3.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../imagenesRobot/" + 3 + ".png")));
        this.btn4.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../imagenesRobot/" + 4 + ".png")));
        this.btn5.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../imagenesRobot/" + 5 + ".png")));
        this.btn6.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../imagenesRobot/" + 6 + ".png")));
        this.btn7.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../imagenesRobot/" + 7 + ".png")));
        this.btn8.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../imagenesRobot/" + 8 + ".png")));
        btn1.setVisible(true);
        btn2.setVisible(true);
        btn3.setVisible(true);
        btn4.setVisible(true);
        btn5.setVisible(true);
        btn6.setVisible(true);
        btn7.setVisible(true);
        btn8.setVisible(true);
        btn9.setVisible(false);

        cont = 1;
        int n = 8;  //numeros aleatorios
        int k = n;  //auxiliar;
        int[] numeros = new int[n];
        int[] valor = new int[n];
        Random rnd = new Random();
        int res;

        //se rellena una matriz ordenada del 1 al 9(1..n)
        for (int i = 0; i < n; i++) {
            numeros[i] = i + 1;
        }

        for (int i = 0; i < n; i++) {
            res = rnd.nextInt(k);
            valor[i] = numeros[res];
            numeros[res] = numeros[k - 1];
            k--;
            System.out.println(valor[i]);
        }
        System.out.println("------------------------------------------");

        btn1.setText(String.valueOf(valor[0]));
        btn2.setText(String.valueOf(valor[1]));
        btn3.setText(String.valueOf(valor[2]));
        btn4.setText(String.valueOf(valor[3]));
        btn5.setText(String.valueOf(valor[4]));
        btn6.setText(String.valueOf(valor[5]));
        btn7.setText(String.valueOf(valor[6]));
        btn8.setText(String.valueOf(valor[7]));

        btn9.setVisible(false);//espacio que permite realizar los moviemientos en le PUZZLE

        System.out.println("------------------------------------------");
        this.btn1.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../imagenesRobot/" + valor[0] + ".png")));
        this.btn2.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../imagenesRobot/" + valor[1] + ".png")));
        this.btn3.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../imagenesRobot/" + valor[2] + ".png")));
        this.btn4.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../imagenesRobot/" + valor[3] + ".png")));
        this.btn5.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../imagenesRobot/" + valor[4] + ".png")));
        this.btn6.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../imagenesRobot/" + valor[5] + ".png")));
        this.btn7.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../imagenesRobot/" + valor[6] + ".png")));
        this.btn8.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../imagenesRobot/" + valor[7] + ".png")));
        btn9.setVisible(false);
        jLabelMuestra.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../imagenesRobot/robot.png")));


    }//GEN-LAST:event_jMenuRobotActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
        // TODO add your handling code here:
        cont = 0;
        i = 1;
        jLabel2.setText(String.valueOf("0"));
        btn1.setText("1");
        btn2.setText("2");
        btn3.setText("3");
        btn5.setText("4");
        btn6.setText("5");
        btn7.setText("6");
        btn8.setText("7");
        btn9.setText("9");
        this.btn1.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../paisaje/" + 1 + ".png")));
        this.btn2.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../paisaje/" + 2 + ".png")));
        this.btn3.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../paisaje/" + 3 + ".png")));
        this.btn4.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../paisaje/" + 4 + ".png")));
        this.btn5.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../paisaje/" + 5 + ".png")));
        this.btn6.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../paisaje/" + 6 + ".png")));
        this.btn7.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../paisaje/" + 7 + ".png")));
        this.btn8.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../paisaje/" + 8 + ".png")));
        btn1.setVisible(true);
        btn2.setVisible(true);
        btn3.setVisible(true);
        btn4.setVisible(true);
        btn5.setVisible(true);
        btn6.setVisible(true);
        btn7.setVisible(true);
        btn8.setVisible(true);
        btn9.setVisible(false);

        cont = 1;
        int n = 8;  //numeros aleatorios
        int k = n;  //auxiliar;
        int[] numeros = new int[n];
        int[] valor = new int[n];
        Random rnd = new Random();
        int res;

        //se rellena una matriz ordenada del 1 al 9(1..n)
        for (int i = 0; i < n; i++) {
            numeros[i] = i + 1;
        }

        for (int i = 0; i < n; i++) {
            res = rnd.nextInt(k);
            valor[i] = numeros[res];
            numeros[res] = numeros[k - 1];
            k--;
            System.out.println(valor[i]);
        }
        System.out.println("------------------------------------------");

        btn1.setText(String.valueOf(valor[0]));
        btn2.setText(String.valueOf(valor[1]));
        btn3.setText(String.valueOf(valor[2]));
        btn4.setText(String.valueOf(valor[3]));
        btn5.setText(String.valueOf(valor[4]));
        btn6.setText(String.valueOf(valor[5]));
        btn7.setText(String.valueOf(valor[6]));
        btn8.setText(String.valueOf(valor[7]));

        btn9.setVisible(false);//espacio que permite realizar los moviemientos en le PUZZLE

        System.out.println("------------------------------------------");
        this.btn1.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../paisaje/" + valor[0] + ".png")));
        this.btn2.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../paisaje/" + valor[1] + ".png")));
        this.btn3.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../paisaje/" + valor[2] + ".png")));
        this.btn4.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../paisaje/" + valor[3] + ".png")));
        this.btn5.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../paisaje/" + valor[4] + ".png")));
        this.btn6.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../paisaje/" + valor[5] + ".png")));
        this.btn7.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../paisaje/" + valor[6] + ".png")));
        this.btn8.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../paisaje/" + valor[7] + ".png")));
        btn9.setVisible(false);
        jLabelMuestra.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("../paisaje/paisaje2.png")));
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMenuMario;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelMuestra;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemResolver;
    private javax.swing.JMenuItem jMenuRobot;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panel().setVisible(true);
            }
        });
    }

    private void contarMovimiento() {
        jLabel2.setText(String.valueOf(cont++));
    }

    public void ordenado() {
        String b1 = btn1.getText();
        String b2 = btn2.getText();
        String b3 = btn3.getText();
        String b4 = btn4.getText();
        String b5 = btn5.getText();
        String b6 = btn6.getText();
        String b7 = btn7.getText();
        String b8 = btn8.getText();
        String b9 = btn9.getText();

        if (b1.equals("1") && b2.equals("2") && b3.equals("3") && b4.equals("4")
                && b5.equals("5") && b6.equals("6") && b7.equals("7") && b8.equals("8") && btn9.isVisible() == false) {

            JOptionPane.showMessageDialog(rootPane, "FELICITACIONES UD. GANO!! \n En: " + cont + " Movimientos");
        }
        //System.out.println(b1+b2+b3+b4+b5+b6+b7+b8);       
    }

}
